import type { AgodaHotel } from "./agoda";

// Mock data for development before Agoda API approval.
// Photos are Unsplash — free to use, replace with real Agoda CDN URLs when live.
export const MOCK_HOTELS: AgodaHotel[] = [
  {
    hotelId: 1001,
    hotelName: "Mandarin Oriental Bangkok",
    starRating: 5,
    reviewScore: 9.2,
    reviewCount: 3421,
    imageURL: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800",
    dailyRate: 385,
    crossedOutRate: 520,
    currency: "USD",
    landingURL: "https://www.agoda.com/mandarin-oriental-bangkok?cid=DEMO",
    freeWifi: true,
    freeBreakfast: true,
  },
  {
    hotelId: 1002,
    hotelName: "The Peninsula Bangkok",
    starRating: 5,
    reviewScore: 9.4,
    reviewCount: 2890,
    imageURL: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800",
    dailyRate: 340,
    currency: "USD",
    landingURL: "https://www.agoda.com/peninsula-bangkok?cid=DEMO",
    freeWifi: true,
  },
  {
    hotelId: 1003,
    hotelName: "Sofitel So Bangkok",
    starRating: 5,
    reviewScore: 8.9,
    reviewCount: 1876,
    imageURL: "https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=800",
    dailyRate: 210,
    crossedOutRate: 280,
    currency: "USD",
    landingURL: "https://www.agoda.com/sofitel-so-bangkok?cid=DEMO",
    freeWifi: true,
    freeBreakfast: true,
  },
  {
    hotelId: 1004,
    hotelName: "Riva Surya Bangkok",
    starRating: 4,
    reviewScore: 8.5,
    reviewCount: 1245,
    imageURL: "https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=800",
    dailyRate: 95,
    currency: "USD",
    landingURL: "https://www.agoda.com/riva-surya-bangkok?cid=DEMO",
    freeWifi: true,
  },
  {
    hotelId: 1005,
    hotelName: "Chatrium Riverside Bangkok",
    starRating: 5,
    reviewScore: 8.8,
    reviewCount: 4102,
    imageURL: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800",
    dailyRate: 145,
    crossedOutRate: 195,
    currency: "USD",
    landingURL: "https://www.agoda.com/chatrium-riverside?cid=DEMO",
    freeWifi: true,
  },
  {
    hotelId: 1006,
    hotelName: "Anantara Riverside Bangkok Resort",
    starRating: 5,
    reviewScore: 9.0,
    reviewCount: 2567,
    imageURL: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800",
    dailyRate: 245,
    currency: "USD",
    landingURL: "https://www.agoda.com/anantara-riverside?cid=DEMO",
    freeWifi: true,
    freeBreakfast: true,
  },
  {
    hotelId: 1007,
    hotelName: "Volve Hotel Bangkok",
    starRating: 4,
    reviewScore: 8.3,
    reviewCount: 890,
    imageURL: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800",
    dailyRate: 78,
    currency: "USD",
    landingURL: "https://www.agoda.com/volve-hotel?cid=DEMO",
    freeWifi: true,
  },
  {
    hotelId: 1008,
    hotelName: "Bangkok Marriott Marquis Queen's Park",
    starRating: 5,
    reviewScore: 8.7,
    reviewCount: 5321,
    imageURL: "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=800",
    dailyRate: 175,
    crossedOutRate: 225,
    currency: "USD",
    landingURL: "https://www.agoda.com/marriott-marquis?cid=DEMO",
    freeWifi: true,
    freeBreakfast: true,
  },
  {
    hotelId: 1009,
    hotelName: "Ibis Styles Bangkok Sukhumvit 4",
    starRating: 3,
    reviewScore: 8.1,
    reviewCount: 1543,
    imageURL: "https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=800",
    dailyRate: 52,
    currency: "USD",
    landingURL: "https://www.agoda.com/ibis-styles-sukhumvit?cid=DEMO",
    freeWifi: true,
  },
];
